/* Generated By:JavaCC: Do not edit this line. logoLanguageConstants.java */
package lym;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface logoLanguageConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int FORWARD = 5;
  /** RegularExpression Id. */
  int RIGHT = 6;
  /** RegularExpression Id. */
  int LEFT = 7;
  /** RegularExpression Id. */
  int PENUP = 8;
  /** RegularExpression Id. */
  int PENDOWN = 9;
  /** RegularExpression Id. */
  int REPEAT = 10;
  /** RegularExpression Id. */
  int OPENBRACKET = 11;
  /** RegularExpression Id. */
  int CLOSEBRACKET = 12;
  /** RegularExpression Id. */
  int DIGIT = 13;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "<FORWARD>",
    "<RIGHT>",
    "<LEFT>",
    "<PENUP>",
    "<PENDOWN>",
    "\"REPEAT\"",
    "\"[\"",
    "\"]\"",
    "<DIGIT>",
    "\".\"",
  };

}
